"""Stamp the firmware with the git commit it was built from.

Both AC units run this fork's master, so a fixed "2.8" on the Version topic
said nothing about what is on them (fork issue #13). Before the build, this
writes

    <build dir>/build_version/build_version.h

defining VERSION as the short commit hash, with "-dirty" appended when tracked
files have uncommitted changes, or "unknown" when git is unavailable (a source
archive). The directory goes on the include path and support.h includes the
header. Only the translation units that include it recompile when the hash
changes; a -D flag would rebuild everything, framework included, on every
commit.

A -D VERSION=... build flag still wins: the header is #ifndef-guarded like
every other default in support.h.
"""

import os
import subprocess

Import("env")  # noqa: F821 -- injected by SCons


def _git(project_dir, *args):
    try:
        done = subprocess.run(
            ["git"] + list(args),
            cwd=project_dir,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            universal_newlines=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    return done.stdout.strip()


def build_version(project_dir):
    commit = _git(project_dir, "rev-parse", "--short=7", "HEAD")
    if not commit:
        return "unknown"
    changes = _git(project_dir, "status", "--porcelain", "--untracked-files=no")
    return commit + "-dirty" if changes else commit


def write_header(directory, version):
    path = os.path.join(directory, "build_version.h")
    content = (
        "// Generated by scripts/build_version.py before every build. Do not edit.\n"
        "#pragma once\n"
        "#ifndef VERSION\n"
        '#define VERSION "%s"\n' % version
        + "#endif\n"
    )
    os.makedirs(directory, exist_ok=True)
    try:
        with open(path) as existing:
            if existing.read() == content:
                return
    except OSError:
        pass
    with open(path, "w") as out:
        out.write(content)


version = build_version(env.subst("$PROJECT_DIR"))  # noqa: F821
gen_dir = os.path.join(env.subst("$BUILD_DIR"), "build_version")  # noqa: F821
write_header(gen_dir, version)
env.Append(CPPPATH=[gen_dir])  # noqa: F821
print("Build version: %s" % version)
